FROM node:18-alpine

WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install --verbose
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html