name: Docker Compose Build and Upload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: your_dockerhub_username

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test using Docker Compose
        run: |
          docker-compose --version
          docker-compose up --build --abort-on-container-exit

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker images
        run: |
          services="nginx postgres redis api client worker"
          for service in $services; do
            docker tag $service:latest $DOCKERHUB_USERNAME/$service:latest
            docker push $DOCKERHUB_USERNAME/$service:latest
          done
